### ISSUE TITLE
Membuat Tampilan About

### ISSUE THREAD

**Issue by ans-4175** [begundal-ug/penyegaran_tl#10]
Tampilan about akan berisi:
- siapa yang membuat
- akun penyegaran_tl
- cara akses ke about dari mana?

**Comment by ans-4175** [comment]
> Sounds good. Aku kira teh bakal separate page, tp mendingan ky gini (didalem modal), biar bisa di dismiss cepet.

Ini jadi dikerjain duluan, sebelum share ke admin/dm twitter penyegaran_tl @anwari666 ?

**Comment by anwari666** [comment]
Bikin modal nya pake apa ya? Urang blm pernah ini hmm

**Comment by ans-4175** [comment]
> Bikin modal nya pake apa ya? Urang blm pernah ini hmm

https://www.npmjs.com/package/react-modal, apakah cukup ya?

**Comment by ans-4175** [comment]
Closed by #30
