### ISSUE TITLE
Refine tombol dalam page dan Membuat tampilan single page

### ISSUE THREAD

**Issue by anwari666** [begundal-ug/penyegaran_tl#26]
Terpikirkan ketika nge share di twitter, alangkah kecenya kalau bisa share url semacam https://penyegaran.ml/123456 , yang kalau dibuka akan selalu pointing ke foto tertentu. Saya udah bikin API nya di #25 

- tampilan single page
- tombol see original tweets di halaman utama, halaman single page
- sekaligus shortening header

**Comment by ans-4175** [comment]
Oh nice, di intent tweetnya bisa begitu, pas swipe ngeshare twitter ke single page.
Tapi nanti tetap ada cek tweet aslinya ke `link` si penyegaran_tl-nya

**Comment by ans-4175** [comment]
> Terpikirkan ketika nge share di twitter, alangkah kecenya kalau bisa share url semacam https://penyegaran.ml/123456 , yang kalau dibuka akan selalu pointing ke foto tertentu. Saya udah bikin API nya di #25

Kepikiran, apakah mending yang ini atau tampilan yang ga random, tapi dari terbanyak likes sorted?

Kalau yang single page gitu, interaksinya berarti yang paling depan itu yang id-nya dulu, terus di belakangnya baru yang lain? Apa interaksi yang buat satu gambar gitu, bukannya mending dari @penyegaran_tl-nya aja kl satu gitu?

**Comment by anwari666** [comment]
> Kepikiran, apakah mending yang ini atau tampilan yang ga random, tapi dari terbanyak likes sorted?

Random dulu aja sekarang mah,... Kl terbanyak likes nanti perlu pagination & mesti nge save cursor dr usernya.

> Kalau yang single page gitu, interaksinya berarti yang paling depan itu yang id-nya dulu, terus di belakangnya baru yang lain? Apa interaksi yang buat satu gambar gitu, bukannya mending dari @penyegaran_tl-nya aja kl satu gitu?

The former. Biar orang yg baru ngebuka bs langsung pakai app nya juga. Btw kayaknya perlu button untuk open original tweet deh, biar bs atribusi ke penyegaran_tl langsung

**Comment by ans-4175** [comment]
> Btw kayaknya perlu button untuk open original tweet deh, biar bs atribusi ke penyegaran_tl langsung

Nah ini yang kusebut kemarin dengan "See Tweet"
Jadi kayaknya di row `Share Tweets` ini ada dua tombol buat share dan seet. Nanti secara tampilan pakai model icon atau glyph aja gimana? biar mudah dikenali

**Comment by anwari666** [comment]
button untuk See Original Tweet diimplemen disini juga ya. Sekalian sama shortening header deh...

**Comment by ans-4175** [comment]
> button untuk See Original Tweet diimplemen disini juga ya. Sekalian sama shortening header deh...

Shortening header yang mana ya?
Bisa issue-nya berarti: single page, add original link src and shortening header?

**Comment by anwari666** [comment]
Maksudnya bikin headernya lebih pendek supaya bs viewable ga scroll. Pengaruh ke margin juga sih
