### ISSUE TITLE
Membuat Tampilan Home

### ISSUE THREAD

**Issue by ans-4175** [begundal-ug/penyegaran_tl#3]
Tampilan home dilengkapi interaksinya

Interaksi lainnya:
- auto refetch
- keterangan swipe

**Comment by ans-4175** [comment]
Auto Refetch kalau mau (1-2 pic sebelum) habis, atau pas habis aja ya @anwari666 ?

**Comment by anwari666** [comment]
Oiya idealnya ada button untuk like & dislike juga. Cek https://github.com/3DJakob/react-tinder-card-demo/blob/master/src/examples/Advanced.js
