### ISSUE TITLE
GA not sending data?

### ISSUE THREAD

**Issue by ans-4175** [begundal-ug/penyegaran_tl#34]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/3961872/140076599-33c13373-8460-4965-bce5-ce63076a2ffb.png">
[Link GA](https://analytics.google.com/analytics/web/#/p291751567/reports/)

Dari beberapa hari ini nyoba nyebarin ke teman-teman, pastinya sudah ada yang memakai, atau kita sendiri memakai.
Tapi kok tidak ada data GA Event yang masuk. Kemungkinannya kenapa ya @anwari666 ?

**Comment by anwari666** [comment]
Working on it pak. Sudah sending, tp dari localhost. Events bisa dikirim biasa, tp twitter share blm terkirim otomatis. 

Oya kalau orangnya pakai Firefox, kynya by default ngeblok GA deh... :(

<img width="1413" alt="Screenshot 2021-11-03 at 15 03 09" src="https://user-images.githubusercontent.com/783329/140086151-6386e318-2549-413e-9493-8b59793b8b13.png">
