### ISSUE TITLE
Post Action Swipe

### ISSUE THREAD

**Issue by ans-4175** [begundal-ug/penyegaran_tl#5]
Setiap swipe kanan-kiri akan memberikan score yang dicatat di DB atau Backend

**Comment by ans-4175** [comment]
Apakah ini jadi krusial @anwari666 ? Apa nanti aja, yang penting shareable dulu?
Kalau ga ada ini, berarti kita ga perlu ngejer yang leaderboard juga.

Apa ya kira-kira menariknya interaksi leaderboard atau kita ngumpulin data ini?

**Comment by anwari666** [comment]
Menarik sih, tp nggak krusial... 
Mendingan kita kirim aja dulu data2nya ke google analytics, pake ngirim events & social interactions. Urang bikin isu baru aja buat ini

**Comment by ans-4175** [comment]
Aku kepikiran ini nanti diubah, dicatatnya di localStorage aja gimana?
Sekalian mencatat dia udah swipe apa aja disitu, history-nya dicatat di lokal dan dia bisa lihat mana yang dia meh atau yeah sendiri di localnya

**Comment by anwari666** [comment]
menarik sih. lumayan untuk menyimpan data likes sementara databasenya disiapin. Btw ini ga solve masalah leaderboard itu kan, tetep mesti ada database however simple

**Comment by ans-4175** [comment]
leaderboard-nya ga jadi kl gitu? wkwk
Itu diambil dari data Google Analytics aja gimana?

**Comment by anwari666** [comment]
Nah aku ga tau si GA ini ada public API untuk mengakses resultnya atau ngga.... Dia bisa konek ke Google Data Studio, tp ya itu mah API nya Google yang punya. Perlu eksplor lagi sih... Bikin spike dulu aja apa?
